AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  googleMapsPlaces

  Sample SAM Template for googleMapsPlaces
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  googleMapsPlacesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: googleMapsPlaces/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        googleMapsPlaces:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /googleMapsPlaces
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  googleMapsPlacesApi:
    Description: "API Gateway endpoint URL for Prod stage for googleMapsPlaces function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/googleMapsPlaces/"
  googleMapsPlacesFunction:
    Description: "googleMapsPlaces Lambda Function ARN"
    Value: !GetAtt googleMapsPlacesFunction.Arn
  googleMapsPlacesFunctionIamRole:
    Description: "Implicit IAM Role created for googleMapsPlaces function"
    Value: !GetAtt googleMapsPlacesFunctionRole.Arn
